# Generated by Django 5.0.3 on 2024-03-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_book_isbn13_book_language_code_book_publication_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Author_name',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='page',
            new_name='num_pages',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Book_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
