# Generated by Django 5.0.3 on 2024-03-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_rename_author_name_book_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Book_id',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='book',
            name='language_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='text_reviews_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
