# Generated by Django 5.0.3 on 2024-03-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_book_book_id_alter_book_authors_alter_book_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Book_id',
        ),
    ]
