# Generated by Django 5.0.3 on 2024-03-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_remove_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='members',
            name='outstanding_debt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rent_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
