# Generated by Django 5.0.3 on 2024-03-20 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_alter_book_id_alter_members_outstanding_debt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='outstanding_debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.transaction'),
        ),
    ]
