# Generated by Django 5.0.3 on 2024-03-20 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_alter_members_outstanding_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='return_date',
        ),
        migrations.AlterField(
            model_name='members',
            name='outstanding_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Return_Issue_Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.members')),
            ],
        ),
    ]
