# Generated by Django 5.0.3 on 2024-03-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_remove_transaction_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_issue_book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
